; fizzbuzz
(defun mymod (i n)
  (- i (* n (truncate (/ i n)))))

(print (cons (if (and
  (= 1 (mymod 19 3))
  (= 2 (mymod 20 3))
  (= 0 (mymod 21 3))
  ) 'passed 'failed) '(mymod)))

(defun fizzbuzz (i n)
    (if (<= i n)
      (let* ((x (mymod i 3)) (y (mymod i 5)))
        ; (print (list i n x y))
        (if (or (= x 0) (= y 0))
          (if (and (= x 0) (= y 0))
            (print 'FizzBuzz)
            (if (= x 0)
              (print 'Fizz)
              (print 'Buzz)))
          (print i))
        (fizzbuzz (+ i 1) n))
    nil)
  )
(fizzbuzz 1 20)
